language: node_js
node_js:
  - stable
branches:
  only:
    - master
cache:
  yarn: true

## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test
    - stage: "Deploy"
      name: 'Deploy Docs'
      script: cd docs && yarn && yarn deploy && cd ..
