language: node_js
node_js:
  - stable
cache:
  yarn: true
before_install:
  - echo -e "machine github.ibm.com\n  login $GIT_TOKEN" > ~/.netrc
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test
