language: node_js
node_js:
  - stable
before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test
