language: node_js
node_js:
  - stable
branches:
  only:
    - master
cache:
  yarn: true

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test

script:
  - git config --global user.name "wangkailang"
  - git config --global user.email "2418904055@qq.com"
  - echo "machine github.com login wangkailang password c7202e7c76a3b7f74b48d21b370aeb594bdecf02" > ~/.netrc
  - cd docs && yarn && yarn deploy && cd ..
