language: node_js
node_js:
  - stable
branches:
  only:
    - master
cache:
  yarn: true

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test
    - stage: "Deploys"
      name: "Deploy Docs"
      script: yarn test 

deploy:
  provider: script
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  script: cd docs && yarn && yarn deploy && cd ..
  skip_cleanup: true
  on:
    branch: master
